export const BLOCK_CATEGORIES = [
  "Motion",
  "Light Speaker",
  "Sensor",
  "Event",
  "Loop",
  "Logic",
  "Math",
  "Variable",
  "AI",
  "Patrol line",
  "My Blocks",
  "C Code",
] as const;

export type BlockCategory = typeof BLOCK_CATEGORIES[number];

export type RuntimeStatus =
  | "implemented"
  | "telemetry-only"
  | "stub"
  | "blocked-by-sandbox";

export type BlockKind =
  | "statement"
  | "hat"
  | "c-block"
  | "reporter"
  | "reporter-number"
  | "boolean"
  | "button-dialog"
  | "custom-code";

export type FieldKind =
  | "number"
  | "text"
  | "dropdown"
  | "color"
  | "boolean"
  | "value-input"
  | "boolean-input"
  | "statement-input"
  | "textarea"
  | "matrix";

export interface BlockFieldSchema {
  name: string;
  kind: FieldKind;
  defaultValue: string | number | boolean | null;
  values?: readonly string[];
  unit?: string;
  min?: number;
  max?: number;
  required?: boolean;
}

export interface BlockRegistryEntry {
  type: string;
  category: BlockCategory;
  displayText: string;
  kind: BlockKind;
  fields: readonly BlockFieldSchema[];
  runtimeStatus: RuntimeStatus;
  generatorHandlerId: string;
  runtimeHandlerId: string;
  irV2Op: string;
  notes?: string;
}

const MOTOR_PORTS = ["A", "B", "C", "D", "all"] as const;
const PORTS = ["1", "2", "3", "4", "5"] as const;
const DIRECTIONS = ["Forward", "Backward"] as const;
const TURN_DIRECTIONS = ["Turn left", "Turn right"] as const;
const BRANCHES = ["left", "middle", "right", "T/Cross intersection"] as const;
const COMPARE_OPS = ["<", ">", "=", "!=", "<=", ">="] as const;
const ANGLE_UNITS = ["degree", "radian"] as const;
const MATH_UNARY_OPS = [
  "abs",
  "floor",
  "ceiling",
  "sqrt",
  "sin",
  "cos",
  "tan",
  "asin",
  "acos",
  "atan",
  "ln",
  "log",
  "e^",
  "10^",
] as const;
const COLORS = ["red", "green", "blue", "yellow", "white", "black"] as const;

function field(
  name: string,
  kind: FieldKind,
  defaultValue: string | number | boolean | null,
  options: Partial<Omit<BlockFieldSchema, "name" | "kind" | "defaultValue">> = {},
): BlockFieldSchema {
  return { name, kind, defaultValue, ...options };
}

function entry(entry: BlockRegistryEntry): BlockRegistryEntry {
  return entry;
}

const noFields: readonly BlockFieldSchema[] = [];

export const WHALESBOT_BLOCK_REGISTRY = [
  entry({
    type: "motion_tank_drive_continuous",
    category: "Motion",
    displayText: "move left motor A right motor B Forward power 40 %",
    kind: "statement",
    fields: [
      field("leftMotor", "dropdown", "A", { values: MOTOR_PORTS }),
      field("rightMotor", "dropdown", "B", { values: MOTOR_PORTS }),
      field("direction", "dropdown", "Forward", { values: DIRECTIONS }),
      field("power", "number", 40, { min: -100, max: 100, unit: "percent" }),
    ],
    runtimeStatus: "implemented",
    generatorHandlerId: "motion.tankDriveContinuous",
    runtimeHandlerId: "runtime.motor.setPair",
    irV2Op: "motion.setMotorPair",
  }),
  entry({
    type: "motion_tank_drive_seconds",
    category: "Motion",
    displayText: "move left motor A right motor B Forward power 40 % run for 1 secs.",
    kind: "statement",
    fields: [
      field("leftMotor", "dropdown", "A", { values: MOTOR_PORTS }),
      field("rightMotor", "dropdown", "B", { values: MOTOR_PORTS }),
      field("direction", "dropdown", "Forward", { values: DIRECTIONS }),
      field("power", "number", 40, { min: -100, max: 100, unit: "percent" }),
      field("seconds", "number", 1, { min: 0, unit: "seconds" }),
    ],
    runtimeStatus: "implemented",
    generatorHandlerId: "motion.tankDriveSeconds",
    runtimeHandlerId: "runtime.motor.setPairForTime",
    irV2Op: "motion.setMotorPairForTime",
  }),
  entry({
    type: "motion_stop_pair",
    category: "Motion",
    displayText: "stop left motor A right motor B",
    kind: "statement",
    fields: [
      field("leftMotor", "dropdown", "A", { values: MOTOR_PORTS }),
      field("rightMotor", "dropdown", "B", { values: MOTOR_PORTS }),
    ],
    runtimeStatus: "implemented",
    generatorHandlerId: "motion.stopPair",
    runtimeHandlerId: "runtime.motor.stopPair",
    irV2Op: "motion.stopMotorPair",
  }),
  entry({
    type: "motion_single_motor_power",
    category: "Motion",
    displayText: "set motor A power 40 %",
    kind: "statement",
    fields: [
      field("motor", "dropdown", "A", { values: MOTOR_PORTS }),
      field("power", "number", 40, { min: -100, max: 100, unit: "percent" }),
    ],
    runtimeStatus: "implemented",
    generatorHandlerId: "motion.singleMotorPower",
    runtimeHandlerId: "runtime.motor.setSingle",
    irV2Op: "motion.setMotor",
  }),
  entry({
    type: "motion_dual_motor_seconds",
    category: "Motion",
    displayText: "set motor A power 40 % motor B power 40 % run for 1 secs.",
    kind: "statement",
    fields: [
      field("motorA", "dropdown", "A", { values: MOTOR_PORTS }),
      field("powerA", "number", 40, { min: -100, max: 100, unit: "percent" }),
      field("motorB", "dropdown", "B", { values: MOTOR_PORTS }),
      field("powerB", "number", 40, { min: -100, max: 100, unit: "percent" }),
      field("seconds", "number", 1, { min: 0, unit: "seconds" }),
    ],
    runtimeStatus: "implemented",
    generatorHandlerId: "motion.dualMotorSeconds",
    runtimeHandlerId: "runtime.motor.setPairForTime",
    irV2Op: "motion.setMotorPairForTime",
  }),
  entry({
    type: "motion_single_motor_seconds",
    category: "Motion",
    displayText: "set motor A power 40 % run for 1 secs.",
    kind: "statement",
    fields: [
      field("motor", "dropdown", "A", { values: MOTOR_PORTS }),
      field("power", "number", 40, { min: -100, max: 100, unit: "percent" }),
      field("seconds", "number", 1, { min: 0, unit: "seconds" }),
    ],
    runtimeStatus: "implemented",
    generatorHandlerId: "motion.singleMotorSeconds",
    runtimeHandlerId: "runtime.motor.setSingleForTime",
    irV2Op: "motion.setMotorForTime",
  }),
  entry({
    type: "motion_dual_motor_degrees",
    category: "Motion",
    displayText: "set motor A power 40 % motor B power 40 % rotate for 360 degrees",
    kind: "statement",
    fields: [
      field("motorA", "dropdown", "A", { values: MOTOR_PORTS }),
      field("powerA", "number", 40, { min: -100, max: 100, unit: "percent" }),
      field("motorB", "dropdown", "B", { values: MOTOR_PORTS }),
      field("powerB", "number", 40, { min: -100, max: 100, unit: "percent" }),
      field("degrees", "number", 360, { unit: "encoder degrees" }),
    ],
    runtimeStatus: "stub",
    generatorHandlerId: "motion.dualMotorDegrees",
    runtimeHandlerId: "runtime.diagnostic.encoderNotImplemented",
    irV2Op: "motion.setMotorPairForEncoderDegrees",
  }),
  entry({
    type: "motion_single_motor_degrees",
    category: "Motion",
    displayText: "set motor A power 40 % rotate for 360 degrees",
    kind: "statement",
    fields: [
      field("motor", "dropdown", "A", { values: MOTOR_PORTS }),
      field("power", "number", 40, { min: -100, max: 100, unit: "percent" }),
      field("degrees", "number", 360, { unit: "encoder degrees" }),
    ],
    runtimeStatus: "stub",
    generatorHandlerId: "motion.singleMotorDegrees",
    runtimeHandlerId: "runtime.diagnostic.encoderNotImplemented",
    irV2Op: "motion.setMotorForEncoderDegrees",
  }),
  entry({
    type: "motion_reverse_motor",
    category: "Motion",
    displayText: "reverse motor A",
    kind: "statement",
    fields: [field("motor", "dropdown", "A", { values: MOTOR_PORTS })],
    runtimeStatus: "implemented",
    generatorHandlerId: "motion.reverseMotor",
    runtimeHandlerId: "runtime.motor.reverse",
    irV2Op: "motion.reverseMotor",
  }),
  entry({
    type: "motion_stop_motor",
    category: "Motion",
    displayText: "stop motor all",
    kind: "statement",
    fields: [field("motor", "dropdown", "all", { values: MOTOR_PORTS })],
    runtimeStatus: "implemented",
    generatorHandlerId: "motion.stopMotor",
    runtimeHandlerId: "runtime.motor.stop",
    irV2Op: "motion.stopMotor",
  }),
  entry({
    type: "motion_omni_move",
    category: "Motion",
    displayText: "omni-wheel move power 40 % towards 0 degree",
    kind: "statement",
    fields: [
      field("power", "number", 40, { min: -100, max: 100, unit: "percent" }),
      field("headingDegrees", "number", 0, { unit: "degrees" }),
    ],
    runtimeStatus: "stub",
    generatorHandlerId: "motion.omniMove",
    runtimeHandlerId: "runtime.diagnostic.omniDriveNotImplemented",
    irV2Op: "motion.omniMove",
  }),
  entry({
    type: "motion_omni_turn",
    category: "Motion",
    displayText: "omni-wheel turn Turn left power 40 %",
    kind: "statement",
    fields: [
      field("direction", "dropdown", "Turn left", { values: TURN_DIRECTIONS }),
      field("power", "number", 40, { min: -100, max: 100, unit: "percent" }),
    ],
    runtimeStatus: "stub",
    generatorHandlerId: "motion.omniTurn",
    runtimeHandlerId: "runtime.diagnostic.omniDriveNotImplemented",
    irV2Op: "motion.omniTurn",
  }),
  entry({
    type: "motion_omni_stop",
    category: "Motion",
    displayText: "stop omni-wheel move",
    kind: "statement",
    fields: noFields,
    runtimeStatus: "stub",
    generatorHandlerId: "motion.omniStop",
    runtimeHandlerId: "runtime.diagnostic.omniDriveNotImplemented",
    irV2Op: "motion.omniStop",
  }),
  entry({
    type: "motion_steering_angle_mode",
    category: "Motion",
    displayText: "set up steering gear angle mode ID 1 speed 40 angle 0",
    kind: "statement",
    fields: [
      field("id", "number", 1, { min: 1 }),
      field("speed", "number", 40, { min: 0, max: 100 }),
      field("angle", "number", 0, { unit: "degrees" }),
    ],
    runtimeStatus: "telemetry-only",
    generatorHandlerId: "motion.steeringAngleMode",
    runtimeHandlerId: "runtime.telemetry.steeringGear",
    irV2Op: "motion.steeringGearAngle",
  }),
  entry({
    type: "motion_steering_rotation_mode",
    category: "Motion",
    displayText: "set up steering gear rotation mode ID 1 speed 40",
    kind: "statement",
    fields: [
      field("id", "number", 1, { min: 1 }),
      field("speed", "number", 40, { min: -100, max: 100 }),
    ],
    runtimeStatus: "telemetry-only",
    generatorHandlerId: "motion.steeringRotationMode",
    runtimeHandlerId: "runtime.telemetry.steeringGear",
    irV2Op: "motion.steeringGearRotation",
  }),
  entry({
    type: "motion_restore_steering_torque",
    category: "Motion",
    displayText: "restore steering torque",
    kind: "statement",
    fields: noFields,
    runtimeStatus: "telemetry-only",
    generatorHandlerId: "motion.restoreSteeringTorque",
    runtimeHandlerId: "runtime.telemetry.steeringGear",
    irV2Op: "motion.restoreSteeringTorque",
  }),
  entry({
    type: "event_program_execute",
    category: "Event",
    displayText: "When program execute",
    kind: "hat",
    fields: noFields,
    runtimeStatus: "implemented",
    generatorHandlerId: "event.programExecute",
    runtimeHandlerId: "runtime.program.entryPoint",
    irV2Op: "event.programExecute",
  }),
  entry({
    type: "event_touch_switch_pressed",
    category: "Event",
    displayText: "when touch switch is pressed port 1",
    kind: "hat",
    fields: [field("port", "dropdown", "1", { values: PORTS })],
    runtimeStatus: "stub",
    generatorHandlerId: "event.touchSwitchPressed",
    runtimeHandlerId: "runtime.diagnostic.asyncEventsNotImplemented",
    irV2Op: "event.touchSwitchPressed",
  }),
  entry({
    type: "loop_repeat_forever",
    category: "Loop",
    displayText: "repeat forever",
    kind: "c-block",
    fields: [field("do", "statement-input", null)],
    runtimeStatus: "implemented",
    generatorHandlerId: "loop.repeatForever",
    runtimeHandlerId: "runtime.control.repeatForever",
    irV2Op: "control.repeatForever",
  }),
  entry({
    type: "loop_repeat_times",
    category: "Loop",
    displayText: "repeat 10 times",
    kind: "c-block",
    fields: [
      field("times", "number", 10, { min: 0 }),
      field("do", "statement-input", null),
    ],
    runtimeStatus: "implemented",
    generatorHandlerId: "loop.repeatTimes",
    runtimeHandlerId: "runtime.control.repeatTimes",
    irV2Op: "control.repeatTimes",
  }),
  entry({
    type: "loop_while_condition",
    category: "Loop",
    displayText: "if [condition] repeat",
    kind: "c-block",
    fields: [
      field("condition", "boolean-input", null, { required: true }),
      field("do", "statement-input", null),
    ],
    runtimeStatus: "stub",
    generatorHandlerId: "loop.whileCondition",
    runtimeHandlerId: "runtime.diagnostic.booleanFlowNotImplemented",
    irV2Op: "control.while",
  }),
  entry({
    type: "loop_repeat_until",
    category: "Loop",
    displayText: "repeat until [condition]",
    kind: "c-block",
    fields: [
      field("condition", "boolean-input", null, { required: true }),
      field("do", "statement-input", null),
    ],
    runtimeStatus: "stub",
    generatorHandlerId: "loop.repeatUntil",
    runtimeHandlerId: "runtime.diagnostic.booleanFlowNotImplemented",
    irV2Op: "control.repeatUntil",
  }),
  entry({
    type: "loop_break",
    category: "Loop",
    displayText: "break",
    kind: "statement",
    fields: noFields,
    runtimeStatus: "stub",
    generatorHandlerId: "loop.break",
    runtimeHandlerId: "runtime.diagnostic.loopBreakNotImplemented",
    irV2Op: "control.break",
  }),
  entry({
    type: "loop_return_value",
    category: "Loop",
    displayText: "Return [value]",
    kind: "statement",
    fields: [field("value", "value-input", null)],
    runtimeStatus: "stub",
    generatorHandlerId: "loop.returnValue",
    runtimeHandlerId: "runtime.diagnostic.functionsNotImplemented",
    irV2Op: "control.return",
  }),
  entry({
    type: "loop_wait_seconds",
    category: "Loop",
    displayText: "wait 2 secs.",
    kind: "statement",
    fields: [field("seconds", "number", 2, { min: 0, unit: "seconds" })],
    runtimeStatus: "implemented",
    generatorHandlerId: "loop.waitSeconds",
    runtimeHandlerId: "runtime.control.waitTicks",
    irV2Op: "control.waitSeconds",
  }),
  entry({
    type: "loop_wait_until",
    category: "Loop",
    displayText: "wait until [condition]",
    kind: "statement",
    fields: [field("condition", "boolean-input", null, { required: true })],
    runtimeStatus: "stub",
    generatorHandlerId: "loop.waitUntil",
    runtimeHandlerId: "runtime.diagnostic.booleanFlowNotImplemented",
    irV2Op: "control.waitUntil",
  }),
  entry({
    type: "logic_if_then",
    category: "Logic",
    displayText: "if [condition] then",
    kind: "c-block",
    fields: [
      field("condition", "boolean-input", null, { required: true }),
      field("then", "statement-input", null),
    ],
    runtimeStatus: "stub",
    generatorHandlerId: "logic.ifThen",
    runtimeHandlerId: "runtime.diagnostic.booleanFlowNotImplemented",
    irV2Op: "control.if",
  }),
  entry({
    type: "logic_if_then_else",
    category: "Logic",
    displayText: "if [condition] then else",
    kind: "c-block",
    fields: [
      field("condition", "boolean-input", null, { required: true }),
      field("then", "statement-input", null),
      field("else", "statement-input", null),
    ],
    runtimeStatus: "stub",
    generatorHandlerId: "logic.ifThenElse",
    runtimeHandlerId: "runtime.diagnostic.booleanFlowNotImplemented",
    irV2Op: "control.ifElse",
  }),
  entry({
    type: "logic_compare_lt",
    category: "Logic",
    displayText: "[a] < [b]",
    kind: "boolean",
    fields: [field("a", "value-input", null), field("b", "value-input", null)],
    runtimeStatus: "stub",
    generatorHandlerId: "logic.compareLt",
    runtimeHandlerId: "runtime.diagnostic.expressionsNotImplemented",
    irV2Op: "boolean.compare",
  }),
  entry({
    type: "logic_compare_gt",
    category: "Logic",
    displayText: "[a] > [b]",
    kind: "boolean",
    fields: [field("a", "value-input", null), field("b", "value-input", null)],
    runtimeStatus: "stub",
    generatorHandlerId: "logic.compareGt",
    runtimeHandlerId: "runtime.diagnostic.expressionsNotImplemented",
    irV2Op: "boolean.compare",
  }),
  entry({
    type: "logic_compare_eq",
    category: "Logic",
    displayText: "[a] = [b]",
    kind: "boolean",
    fields: [field("a", "value-input", null), field("b", "value-input", null)],
    runtimeStatus: "stub",
    generatorHandlerId: "logic.compareEq",
    runtimeHandlerId: "runtime.diagnostic.expressionsNotImplemented",
    irV2Op: "boolean.compare",
  }),
  entry({
    type: "logic_compare_neq",
    category: "Logic",
    displayText: "[a] not equal [b]",
    kind: "boolean",
    fields: [field("a", "value-input", null), field("b", "value-input", null)],
    runtimeStatus: "stub",
    generatorHandlerId: "logic.compareNeq",
    runtimeHandlerId: "runtime.diagnostic.expressionsNotImplemented",
    irV2Op: "boolean.compare",
  }),
  entry({
    type: "logic_and",
    category: "Logic",
    displayText: "[cond1] and [cond2]",
    kind: "boolean",
    fields: [field("cond1", "boolean-input", null), field("cond2", "boolean-input", null)],
    runtimeStatus: "stub",
    generatorHandlerId: "logic.and",
    runtimeHandlerId: "runtime.diagnostic.expressionsNotImplemented",
    irV2Op: "boolean.and",
  }),
  entry({
    type: "logic_or",
    category: "Logic",
    displayText: "[cond1] or [cond2]",
    kind: "boolean",
    fields: [field("cond1", "boolean-input", null), field("cond2", "boolean-input", null)],
    runtimeStatus: "stub",
    generatorHandlerId: "logic.or",
    runtimeHandlerId: "runtime.diagnostic.expressionsNotImplemented",
    irV2Op: "boolean.or",
  }),
  entry({
    type: "logic_not",
    category: "Logic",
    displayText: "not [condition]",
    kind: "boolean",
    fields: [field("condition", "boolean-input", null)],
    runtimeStatus: "stub",
    generatorHandlerId: "logic.not",
    runtimeHandlerId: "runtime.diagnostic.expressionsNotImplemented",
    irV2Op: "boolean.not",
  }),
  entry({
    type: "math_add",
    category: "Math",
    displayText: "[10] + [10]",
    kind: "reporter-number",
    fields: [field("left", "value-input", 10), field("right", "value-input", 10)],
    runtimeStatus: "stub",
    generatorHandlerId: "math.add",
    runtimeHandlerId: "runtime.diagnostic.expressionsNotImplemented",
    irV2Op: "value.binary",
  }),
  entry({
    type: "math_subtract",
    category: "Math",
    displayText: "[10] - [10]",
    kind: "reporter-number",
    fields: [field("left", "value-input", 10), field("right", "value-input", 10)],
    runtimeStatus: "stub",
    generatorHandlerId: "math.subtract",
    runtimeHandlerId: "runtime.diagnostic.expressionsNotImplemented",
    irV2Op: "value.binary",
  }),
  entry({
    type: "math_multiply",
    category: "Math",
    displayText: "[10] x [10]",
    kind: "reporter-number",
    fields: [field("left", "value-input", 10), field("right", "value-input", 10)],
    runtimeStatus: "stub",
    generatorHandlerId: "math.multiply",
    runtimeHandlerId: "runtime.diagnostic.expressionsNotImplemented",
    irV2Op: "value.binary",
  }),
  entry({
    type: "math_divide",
    category: "Math",
    displayText: "[10] / [10]",
    kind: "reporter-number",
    fields: [field("left", "value-input", 10), field("right", "value-input", 10)],
    runtimeStatus: "stub",
    generatorHandlerId: "math.divide",
    runtimeHandlerId: "runtime.diagnostic.expressionsNotImplemented",
    irV2Op: "value.binary",
  }),
  entry({
    type: "math_random_range",
    category: "Math",
    displayText: "pick random from 0 to 10",
    kind: "reporter-number",
    fields: [field("min", "number", 0), field("max", "number", 10)],
    runtimeStatus: "stub",
    generatorHandlerId: "math.randomRange",
    runtimeHandlerId: "runtime.diagnostic.expressionsNotImplemented",
    irV2Op: "value.randomRange",
  }),
  entry({
    type: "math_modulo",
    category: "Math",
    displayText: "the remainder of dividing [a] by [b]",
    kind: "reporter-number",
    fields: [field("a", "value-input", null), field("b", "value-input", null)],
    runtimeStatus: "stub",
    generatorHandlerId: "math.modulo",
    runtimeHandlerId: "runtime.diagnostic.expressionsNotImplemented",
    irV2Op: "value.modulo",
  }),
  entry({
    type: "math_round",
    category: "Math",
    displayText: "round [x]",
    kind: "reporter-number",
    fields: [field("value", "value-input", null)],
    runtimeStatus: "stub",
    generatorHandlerId: "math.round",
    runtimeHandlerId: "runtime.diagnostic.expressionsNotImplemented",
    irV2Op: "value.round",
  }),
  entry({
    type: "math_unary_function",
    category: "Math",
    displayText: "abs [x]",
    kind: "reporter-number",
    fields: [
      field("op", "dropdown", "abs", { values: MATH_UNARY_OPS }),
      field("value", "value-input", null),
      field("angleUnit", "dropdown", "degree", { values: ANGLE_UNITS }),
    ],
    runtimeStatus: "stub",
    generatorHandlerId: "math.unaryFunction",
    runtimeHandlerId: "runtime.diagnostic.expressionsNotImplemented",
    irV2Op: "value.unary",
    notes: "Trig and inverse trig carry explicit degree/radian units.",
  }),
  entry({
    type: "variable_create",
    category: "Variable",
    displayText: "Create a variable",
    kind: "button-dialog",
    fields: [field("variableName", "text", "my variable", { required: true })],
    runtimeStatus: "stub",
    generatorHandlerId: "variable.create",
    runtimeHandlerId: "runtime.diagnostic.variablesNotImplemented",
    irV2Op: "variable.declare",
  }),
  entry({
    type: "change_var_v2",
    category: "Variable",
    displayText: "Change variable by [value]",
    kind: "statement",
    fields: [
      field("variableName", "text", "v0", { required: true }),
      field("delta", "value-input", 1),
    ],
    runtimeStatus: "implemented",
    generatorHandlerId: "variable.change",
    runtimeHandlerId: "runtime.variable.change",
    irV2Op: "variable.change",
  }),
  entry({
    type: "my_blocks_create",
    category: "My Blocks",
    displayText: "Create new blocks",
    kind: "button-dialog",
    fields: [
      field("blockName", "text", "my block", { required: true }),
      field("parameters", "text", "number:boolean:text"),
    ],
    runtimeStatus: "stub",
    generatorHandlerId: "myBlocks.create",
    runtimeHandlerId: "runtime.diagnostic.functionsNotImplemented",
    irV2Op: "function.declare",
  }),
  entry({
    type: "my_block_definition",
    category: "My Blocks",
    displayText: "Define block [name] param [value]",
    kind: "c-block",
    fields: [
      field("name", "text", "my block", { required: true }),
      field("param", "text", "value", { required: true }),
      field("body", "statement-input", null),
    ],
    runtimeStatus: "implemented",
    generatorHandlerId: "myBlocks.definition",
    runtimeHandlerId: "runtime.function.definition",
    irV2Op: "function.declare",
  }),
  entry({
    type: "my_block_call_statement",
    category: "My Blocks",
    displayText: "Call block [name]",
    kind: "statement",
    fields: [
      field("name", "text", "my block", { required: true }),
      field("arg0", "value-input", 1),
    ],
    runtimeStatus: "implemented",
    generatorHandlerId: "myBlocks.callStatement",
    runtimeHandlerId: "runtime.function.call",
    irV2Op: "function.call",
  }),
  entry({
    type: "my_block_call_value",
    category: "My Blocks",
    displayText: "Call block [name] return value",
    kind: "reporter-number",
    fields: [
      field("name", "text", "my block", { required: true }),
      field("arg0", "value-input", 1),
    ],
    runtimeStatus: "implemented",
    generatorHandlerId: "myBlocks.callValue",
    runtimeHandlerId: "runtime.function.callValue",
    irV2Op: "value.call",
  }),
  entry({
    type: "my_block_param_value",
    category: "My Blocks",
    displayText: "parameter [value]",
    kind: "reporter-number",
    fields: [field("param", "text", "value", { required: true })],
    runtimeStatus: "implemented",
    generatorHandlerId: "myBlocks.paramValue",
    runtimeHandlerId: "runtime.function.paramValue",
    irV2Op: "value.parameter",
  }),
  entry({
    type: "patrol_initialize_tank",
    category: "Patrol line",
    displayText: "initialize left motor A 100 right motor B -100 integrated grayscale port 5",
    kind: "statement",
    fields: [
      field("leftMotor", "dropdown", "A", { values: MOTOR_PORTS }),
      field("leftDirection", "number", 100),
      field("rightMotor", "dropdown", "B", { values: MOTOR_PORTS }),
      field("rightDirection", "number", -100),
      field("grayscalePort", "dropdown", "5", { values: PORTS }),
    ],
    runtimeStatus: "implemented",
    generatorHandlerId: "patrol.initializeTank",
    runtimeHandlerId: "runtime.hardware.initializeTank",
    irV2Op: "hardware.initializeTankLineFollower",
  }),
  entry({
    type: "patrol_initialize_omni",
    category: "Patrol line",
    displayText: "initialize omni-wheel Left front motorA 100 Right front motorB 100 Right rear motorC 100 Left rear motorD 100 integrated grayscale port 5",
    kind: "statement",
    fields: [
      field("leftFrontMotor", "dropdown", "A", { values: MOTOR_PORTS }),
      field("rightFrontMotor", "dropdown", "B", { values: MOTOR_PORTS }),
      field("rightRearMotor", "dropdown", "C", { values: MOTOR_PORTS }),
      field("leftRearMotor", "dropdown", "D", { values: MOTOR_PORTS }),
      field("leftFrontDirection", "number", 100),
      field("rightFrontDirection", "number", 100),
      field("rightRearDirection", "number", 100),
      field("leftRearDirection", "number", 100),
      field("grayscalePort", "dropdown", "5", { values: PORTS }),
    ],
    runtimeStatus: "stub",
    generatorHandlerId: "patrol.initializeOmni",
    runtimeHandlerId: "runtime.diagnostic.omniDriveNotImplemented",
    irV2Op: "hardware.initializeOmniLineFollower",
  }),
  entry({
    type: "patrol_black_white_detection",
    category: "Patrol line",
    displayText: "black and white detection",
    kind: "statement",
    fields: noFields,
    runtimeStatus: "implemented",
    generatorHandlerId: "patrol.blackWhiteDetection",
    runtimeHandlerId: "runtime.sensor.calibrateGrayscale",
    irV2Op: "sensor.calibrateGrayscale",
  }),
  entry({
    type: "patrol_line_speed",
    category: "Patrol line",
    displayText: "patrol line speed 30",
    kind: "statement",
    fields: [field("speed", "number", 30, { min: 0, max: 100 })],
    runtimeStatus: "implemented",
    generatorHandlerId: "patrol.lineSpeed",
    runtimeHandlerId: "runtime.lineFollower.continuous",
    irV2Op: "lineFollower.followContinuous",
  }),
  entry({
    type: "patrol_line_for_time",
    category: "Patrol line",
    displayText: "patrol line patrol line speed 30 for 0.5",
    kind: "statement",
    fields: [
      field("speed", "number", 30, { min: 0, max: 100 }),
      field("seconds", "number", 0.5, { min: 0, unit: "seconds" }),
    ],
    runtimeStatus: "implemented",
    generatorHandlerId: "patrol.lineForTime",
    runtimeHandlerId: "runtime.lineFollower.forTime",
    irV2Op: "lineFollower.followForTime",
  }),
  entry({
    type: "patrol_line_intersections",
    category: "Patrol line",
    displayText: "patrol line intersections left patrol line speed 30 rush through intersection time 0",
    kind: "statement",
    fields: [
      field("branch", "dropdown", "left", { values: BRANCHES }),
      field("speed", "number", 30, { min: 0, max: 100 }),
      field("rushSeconds", "number", 0, { min: 0, unit: "seconds" }),
    ],
    runtimeStatus: "implemented",
    generatorHandlerId: "patrol.lineUntilIntersection",
    runtimeHandlerId: "runtime.lineFollower.untilIntersection",
    irV2Op: "lineFollower.untilIntersection",
  }),
  entry({
    type: "patrol_turn_branch",
    category: "Patrol line",
    displayText: "turn middle left motor speed 0 right motor speed 0",
    kind: "statement",
    fields: [
      field("branch", "dropdown", "middle", { values: BRANCHES }),
      field("leftSpeed", "number", 0, { min: -100, max: 100 }),
      field("rightSpeed", "number", 0, { min: -100, max: 100 }),
    ],
    runtimeStatus: "implemented",
    generatorHandlerId: "patrol.turnBranch",
    runtimeHandlerId: "runtime.lineFollower.turnUntilBranch",
    irV2Op: "lineFollower.turnUntilBranch",
  }),
  entry({
    type: "patrol_start_motor_time",
    category: "Patrol line",
    displayText: "start motor left motor speed 20 right motor speed 20 time 0.5",
    kind: "statement",
    fields: [
      field("leftSpeed", "number", 20, { min: -100, max: 100 }),
      field("rightSpeed", "number", 20, { min: -100, max: 100 }),
      field("seconds", "number", 0.5, { min: 0, unit: "seconds" }),
    ],
    runtimeStatus: "implemented",
    generatorHandlerId: "patrol.startMotorTime",
    runtimeHandlerId: "runtime.motor.setPairForTime",
    irV2Op: "motion.setMotorPairForTime",
  }),
  entry({
    type: "patrol_start_motor_angle",
    category: "Patrol line",
    displayText: "start motor left motor speed 20 right motor speed 20 angle 360",
    kind: "statement",
    fields: [
      field("leftSpeed", "number", 20, { min: -100, max: 100 }),
      field("rightSpeed", "number", 20, { min: -100, max: 100 }),
      field("degrees", "number", 360, { unit: "encoder degrees" }),
    ],
    runtimeStatus: "stub",
    generatorHandlerId: "patrol.startMotorAngle",
    runtimeHandlerId: "runtime.diagnostic.encoderNotImplemented",
    irV2Op: "motion.setMotorPairForEncoderDegrees",
  }),
  entry({
    type: "patrol_start_motor_until_sensor",
    category: "Patrol line",
    displayText: "start motor left motor speed 20 right motor speed 20 Sensor 1 < 50",
    kind: "statement",
    fields: [
      field("leftSpeed", "number", 20, { min: -100, max: 100 }),
      field("rightSpeed", "number", 20, { min: -100, max: 100 }),
      field("sensor", "dropdown", "1", { values: PORTS }),
      field("compare", "dropdown", "<", { values: COMPARE_OPS }),
      field("threshold", "number", 50),
    ],
    runtimeStatus: "implemented",
    generatorHandlerId: "patrol.startMotorUntilSensor",
    runtimeHandlerId: "runtime.motor.setPairUntil",
    irV2Op: "motion.setMotorPairUntil",
  }),
  entry({
    type: "patrol_start_button",
    category: "Patrol line",
    displayText: "start button",
    kind: "statement",
    fields: noFields,
    runtimeStatus: "stub",
    generatorHandlerId: "compat.startButton",
    runtimeHandlerId: "runtime.diagnostic.intentionalNoop",
    irV2Op: "compat.startButton",
    notes: "Intentional compatibility stub from doc section 15.",
  }),
  entry({
    type: "light_play_sound",
    category: "Light Speaker",
    displayText: "play sound Greet Hello",
    kind: "statement",
    fields: [
      field("group", "dropdown", "Greet", { values: ["Greet", "Effect", "Animal", "Music"] }),
      field("sound", "dropdown", "Hello", { values: ["Hello"] }),
    ],
    runtimeStatus: "telemetry-only",
    generatorHandlerId: "lightSpeaker.playSound",
    runtimeHandlerId: "runtime.telemetry.sound",
    irV2Op: "effect.playSound",
  }),
  entry({
    type: "light_electromagnet",
    category: "Light Speaker",
    displayText: "electromagnet port 1 absorption",
    kind: "statement",
    fields: [
      field("port", "dropdown", "1", { values: PORTS }),
      field("mode", "dropdown", "absorption", { values: ["absorption", "release"] }),
    ],
    runtimeStatus: "telemetry-only",
    generatorHandlerId: "lightSpeaker.electromagnet",
    runtimeHandlerId: "runtime.telemetry.electromagnet",
    irV2Op: "effect.electromagnet",
  }),
  entry({
    type: "light_emotion_expression",
    category: "Light Speaker",
    displayText: "emotion screen expression [eyes] left eye port 1 right eye port 2",
    kind: "statement",
    fields: [
      field("expression", "dropdown", "eyes", { values: ["eyes"] }),
      field("leftEyePort", "dropdown", "1", { values: PORTS }),
      field("rightEyePort", "dropdown", "2", { values: PORTS }),
    ],
    runtimeStatus: "telemetry-only",
    generatorHandlerId: "lightSpeaker.emotionExpression",
    runtimeHandlerId: "runtime.telemetry.display",
    irV2Op: "effect.emotionExpression",
  }),
  entry({
    type: "light_clear_emotion_expressions",
    category: "Light Speaker",
    displayText: "clear emotion screen expressions left eye port 1 right eye port 2",
    kind: "statement",
    fields: [
      field("leftEyePort", "dropdown", "1", { values: PORTS }),
      field("rightEyePort", "dropdown", "2", { values: PORTS }),
    ],
    runtimeStatus: "telemetry-only",
    generatorHandlerId: "lightSpeaker.clearEmotionExpressions",
    runtimeHandlerId: "runtime.telemetry.display",
    irV2Op: "effect.clearEmotionExpressions",
  }),
  entry({
    type: "light_emotion_symbols",
    category: "Light Speaker",
    displayText: "emotion screen symbols [?] port 1",
    kind: "statement",
    fields: [
      field("symbol", "dropdown", "?", { values: ["?", "!", "heart", "smile"] }),
      field("port", "dropdown", "1", { values: PORTS }),
    ],
    runtimeStatus: "telemetry-only",
    generatorHandlerId: "lightSpeaker.emotionSymbols",
    runtimeHandlerId: "runtime.telemetry.display",
    irV2Op: "effect.emotionSymbol",
  }),
  entry({
    type: "light_emotion_customization",
    category: "Light Speaker",
    displayText: "emotion screen customization [matrix] port 1",
    kind: "statement",
    fields: [
      field("matrix", "matrix", null),
      field("port", "dropdown", "1", { values: PORTS }),
    ],
    runtimeStatus: "telemetry-only",
    generatorHandlerId: "lightSpeaker.emotionCustomization",
    runtimeHandlerId: "runtime.telemetry.display",
    irV2Op: "effect.emotionMatrix",
  }),
  entry({
    type: "light_clear_emotion_screen",
    category: "Light Speaker",
    displayText: "clear emotion screen port 1",
    kind: "statement",
    fields: [field("port", "dropdown", "1", { values: PORTS })],
    runtimeStatus: "telemetry-only",
    generatorHandlerId: "lightSpeaker.clearEmotionScreen",
    runtimeHandlerId: "runtime.telemetry.display",
    irV2Op: "effect.clearEmotionScreen",
  }),
  entry({
    type: "light_reading_1",
    category: "Light Speaker",
    displayText: "reading 1",
    kind: "statement",
    fields: [field("value", "number", 1)],
    runtimeStatus: "stub",
    generatorHandlerId: "compat.reading1",
    runtimeHandlerId: "runtime.diagnostic.intentionalNoop",
    irV2Op: "compat.reading1",
    notes: "Intentional compatibility stub from doc section 15.",
  }),
  entry({
    type: "light_led_rgb",
    category: "Light Speaker",
    displayText: "set LED lights port 1 color R 255 G 255 B 255",
    kind: "statement",
    fields: [
      field("port", "dropdown", "1", { values: PORTS }),
      field("r", "number", 255, { min: 0, max: 255 }),
      field("g", "number", 255, { min: 0, max: 255 }),
      field("b", "number", 255, { min: 0, max: 255 }),
    ],
    runtimeStatus: "telemetry-only",
    generatorHandlerId: "lightSpeaker.ledRgb",
    runtimeHandlerId: "runtime.telemetry.led",
    irV2Op: "effect.setLedRgb",
  }),
  entry({
    type: "light_led_swatch",
    category: "Light Speaker",
    displayText: "set LED lights port 1 color [swatch]",
    kind: "statement",
    fields: [
      field("port", "dropdown", "1", { values: PORTS }),
      field("color", "color", "#ffffff"),
    ],
    runtimeStatus: "telemetry-only",
    generatorHandlerId: "lightSpeaker.ledSwatch",
    runtimeHandlerId: "runtime.telemetry.led",
    irV2Op: "effect.setLedColor",
  }),
  entry({
    type: "light_led_off",
    category: "Light Speaker",
    displayText: "turn off LED port 1",
    kind: "statement",
    fields: [field("port", "dropdown", "1", { values: PORTS })],
    runtimeStatus: "telemetry-only",
    generatorHandlerId: "lightSpeaker.ledOff",
    runtimeHandlerId: "runtime.telemetry.led",
    irV2Op: "effect.turnOffLed",
  }),
  entry({
    type: "light_digital_tube_display",
    category: "Light Speaker",
    displayText: "digital tube port 1 [value]",
    kind: "statement",
    fields: [
      field("port", "dropdown", "1", { values: PORTS }),
      field("value", "value-input", 0),
    ],
    runtimeStatus: "telemetry-only",
    generatorHandlerId: "lightSpeaker.digitalTubeDisplay",
    runtimeHandlerId: "runtime.telemetry.display",
    irV2Op: "effect.digitalTubeDisplay",
  }),
  entry({
    type: "light_clear_digital_tube",
    category: "Light Speaker",
    displayText: "clear digital tube port 1",
    kind: "statement",
    fields: [field("port", "dropdown", "1", { values: PORTS })],
    runtimeStatus: "telemetry-only",
    generatorHandlerId: "lightSpeaker.clearDigitalTube",
    runtimeHandlerId: "runtime.telemetry.display",
    irV2Op: "effect.clearDigitalTube",
  }),
  entry({
    type: "light_screen_display",
    category: "Light Speaker",
    displayText: "screen display [value]",
    kind: "statement",
    fields: [field("value", "value-input", "")],
    runtimeStatus: "telemetry-only",
    generatorHandlerId: "lightSpeaker.screenDisplay",
    runtimeHandlerId: "runtime.telemetry.display",
    irV2Op: "effect.screenDisplay",
  }),
  entry({
    type: "light_clear_screen",
    category: "Light Speaker",
    displayText: "clear screen",
    kind: "statement",
    fields: noFields,
    runtimeStatus: "telemetry-only",
    generatorHandlerId: "lightSpeaker.clearScreen",
    runtimeHandlerId: "runtime.telemetry.display",
    irV2Op: "effect.clearScreen",
  }),
  entry({
    type: "sensor_touch_switch_pressed",
    category: "Sensor",
    displayText: "touch switch 1 pressed",
    kind: "boolean",
    fields: [field("port", "dropdown", "1", { values: PORTS })],
    runtimeStatus: "stub",
    generatorHandlerId: "sensor.touchSwitchPressed",
    runtimeHandlerId: "runtime.diagnostic.sensorNotImplemented",
    irV2Op: "sensor.touchSwitchPressed",
  }),
  entry({
    type: "sensor_infrared_obstacle",
    category: "Sensor",
    displayText: "infrared port 1 obstacles detected",
    kind: "boolean",
    fields: [field("port", "dropdown", "1", { values: PORTS })],
    runtimeStatus: "stub",
    generatorHandlerId: "sensor.infraredObstacle",
    runtimeHandlerId: "runtime.diagnostic.sensorNotImplemented",
    irV2Op: "sensor.infraredObstacle",
  }),
  entry({
    type: "sensor_infrared_range_value",
    category: "Sensor",
    displayText: "infrared ranging sensor port 1 value",
    kind: "reporter-number",
    fields: [field("port", "dropdown", "1", { values: PORTS })],
    runtimeStatus: "stub",
    generatorHandlerId: "sensor.infraredRangeValue",
    runtimeHandlerId: "runtime.diagnostic.sensorNotImplemented",
    irV2Op: "sensor.infraredRange",
  }),
  entry({
    type: "sensor_integrated_grayscale_detect_black",
    category: "Sensor",
    displayText: "integrated grayscale port 5 channel 1 detected black",
    kind: "boolean",
    fields: [
      field("port", "dropdown", "5", { values: PORTS }),
      field("channel", "number", 1, { min: 1, max: 5 }),
    ],
    runtimeStatus: "implemented",
    generatorHandlerId: "sensor.integratedGrayscaleDetectBlack",
    runtimeHandlerId: "runtime.sensor.grayscaleDetectBlack",
    irV2Op: "sensor.grayscaleDetectBlack",
  }),
  entry({
    type: "sensor_integrated_grayscale_value",
    category: "Sensor",
    displayText: "integrated grayscale port 5 channel 1",
    kind: "reporter-number",
    fields: [
      field("port", "dropdown", "5", { values: PORTS }),
      field("channel", "number", 1, { min: 1, max: 5 }),
    ],
    runtimeStatus: "implemented",
    generatorHandlerId: "sensor.integratedGrayscaleValue",
    runtimeHandlerId: "runtime.sensor.grayscaleValue",
    irV2Op: "sensor.grayscaleValue",
  }),
  entry({
    type: "sensor_single_grayscale_detect_black",
    category: "Sensor",
    displayText: "single grayscale port 1 detected black",
    kind: "boolean",
    fields: [field("port", "dropdown", "1", { values: PORTS })],
    runtimeStatus: "implemented",
    generatorHandlerId: "sensor.singleGrayscaleDetectBlack",
    runtimeHandlerId: "runtime.sensor.singleGrayscaleDetectBlack",
    irV2Op: "sensor.singleGrayscaleDetectBlack",
  }),
  entry({
    type: "sensor_single_grayscale_value",
    category: "Sensor",
    displayText: "single grayscale port 1 detected value",
    kind: "reporter-number",
    fields: [field("port", "dropdown", "1", { values: PORTS })],
    runtimeStatus: "implemented",
    generatorHandlerId: "sensor.singleGrayscaleValue",
    runtimeHandlerId: "runtime.sensor.singleGrayscaleValue",
    irV2Op: "sensor.singleGrayscaleValue",
  }),
  entry({
    type: "sensor_ultrasonic_distance",
    category: "Sensor",
    displayText: "ultrasonic sensor port 1 detect distance cm",
    kind: "reporter-number",
    fields: [field("port", "dropdown", "1", { values: PORTS })],
    runtimeStatus: "stub",
    generatorHandlerId: "sensor.ultrasonicDistance",
    runtimeHandlerId: "runtime.diagnostic.sensorNotImplemented",
    irV2Op: "sensor.ultrasonicDistance",
  }),
  entry({
    type: "sensor_ambient_light_value",
    category: "Sensor",
    displayText: "ambient light port 1 value",
    kind: "reporter-number",
    fields: [field("port", "dropdown", "1", { values: PORTS })],
    runtimeStatus: "stub",
    generatorHandlerId: "sensor.ambientLightValue",
    runtimeHandlerId: "runtime.diagnostic.sensorNotImplemented",
    irV2Op: "sensor.ambientLight",
  }),
  entry({
    type: "sensor_temperature_celsius",
    category: "Sensor",
    displayText: "temperature sensor port 1 \u00b0C",
    kind: "reporter-number",
    fields: [field("port", "dropdown", "1", { values: PORTS })],
    runtimeStatus: "stub",
    generatorHandlerId: "sensor.temperatureCelsius",
    runtimeHandlerId: "runtime.diagnostic.sensorNotImplemented",
    irV2Op: "sensor.temperatureCelsius",
  }),
  entry({
    type: "sensor_humidity_percent",
    category: "Sensor",
    displayText: "humidity sensor port 1 value %",
    kind: "reporter-number",
    fields: [field("port", "dropdown", "1", { values: PORTS })],
    runtimeStatus: "stub",
    generatorHandlerId: "sensor.humidityPercent",
    runtimeHandlerId: "runtime.diagnostic.sensorNotImplemented",
    irV2Op: "sensor.humidityPercent",
  }),
  entry({
    type: "sensor_flame_value",
    category: "Sensor",
    displayText: "flame sensor port 1 value",
    kind: "reporter-number",
    fields: [field("port", "dropdown", "1", { values: PORTS })],
    runtimeStatus: "stub",
    generatorHandlerId: "sensor.flameValue",
    runtimeHandlerId: "runtime.diagnostic.sensorNotImplemented",
    irV2Op: "sensor.flameValue",
  }),
  entry({
    type: "sensor_magnetic_detected",
    category: "Sensor",
    displayText: "magnetic port 1 magnetic field detected",
    kind: "boolean",
    fields: [field("port", "dropdown", "1", { values: PORTS })],
    runtimeStatus: "stub",
    generatorHandlerId: "sensor.magneticDetected",
    runtimeHandlerId: "runtime.diagnostic.sensorNotImplemented",
    irV2Op: "sensor.magneticDetected",
  }),
  entry({
    type: "sensor_volume_detection",
    category: "Sensor",
    displayText: "volume detection port 1",
    kind: "reporter-number",
    fields: [field("port", "dropdown", "1", { values: PORTS })],
    runtimeStatus: "stub",
    generatorHandlerId: "sensor.volumeDetection",
    runtimeHandlerId: "runtime.diagnostic.sensorNotImplemented",
    irV2Op: "sensor.volumeDetection",
  }),
  entry({
    type: "sensor_motor_encoder_value",
    category: "Sensor",
    displayText: "motor encoder port A",
    kind: "reporter-number",
    fields: [field("motor", "dropdown", "A", { values: MOTOR_PORTS })],
    runtimeStatus: "implemented",
    generatorHandlerId: "sensor.motorEncoderValue",
    runtimeHandlerId: "runtime.sensor.motorEncoder",
    irV2Op: "sensor.motorEncoder",
  }),
  entry({
    type: "sensor_reset_motor_encoder",
    category: "Sensor",
    displayText: "reset motor encoder port A",
    kind: "statement",
    fields: [field("motor", "dropdown", "A", { values: MOTOR_PORTS })],
    runtimeStatus: "implemented",
    generatorHandlerId: "sensor.resetMotorEncoder",
    runtimeHandlerId: "runtime.sensor.resetMotorEncoder",
    irV2Op: "sensor.resetMotorEncoder",
  }),
  entry({
    type: "sensor_current_timer_value",
    category: "Sensor",
    displayText: "current timer value",
    kind: "reporter-number",
    fields: noFields,
    runtimeStatus: "implemented",
    generatorHandlerId: "sensor.currentTimerValue",
    runtimeHandlerId: "runtime.sensor.timerValue",
    irV2Op: "sensor.timerValue",
  }),
  entry({
    type: "sensor_reset_timer",
    category: "Sensor",
    displayText: "reset timer",
    kind: "statement",
    fields: noFields,
    runtimeStatus: "implemented",
    generatorHandlerId: "sensor.resetTimer",
    runtimeHandlerId: "runtime.sensor.resetTimer",
    irV2Op: "sensor.resetTimer",
  }),
  entry({
    type: "sensor_remote_control_button",
    category: "Sensor",
    displayText: "remote control button",
    kind: "boolean",
    fields: [field("button", "dropdown", "A", { values: ["A", "B", "C", "D", "up", "down", "left", "right"] })],
    runtimeStatus: "stub",
    generatorHandlerId: "compat.remoteControlButton",
    runtimeHandlerId: "runtime.diagnostic.intentionalFalse",
    irV2Op: "compat.remoteControlButton",
    notes: "Intentional compatibility stub from doc section 15.",
  }),
  entry({
    type: "sensor_color_value",
    category: "Sensor",
    displayText: "Color sensor port 1",
    kind: "reporter",
    fields: [field("port", "dropdown", "1", { values: PORTS })],
    runtimeStatus: "stub",
    generatorHandlerId: "sensor.colorValue",
    runtimeHandlerId: "runtime.diagnostic.sensorNotImplemented",
    irV2Op: "sensor.colorValue",
  }),
  entry({
    type: "sensor_color_detected",
    category: "Sensor",
    displayText: "Color sensor port 1 detected red",
    kind: "boolean",
    fields: [
      field("port", "dropdown", "1", { values: PORTS }),
      field("color", "dropdown", "red", { values: COLORS }),
    ],
    runtimeStatus: "stub",
    generatorHandlerId: "sensor.colorDetected",
    runtimeHandlerId: "runtime.diagnostic.sensorNotImplemented",
    irV2Op: "sensor.colorDetected",
  }),
  entry({
    type: "ai_image_recognition",
    category: "AI",
    displayText: "image recognition port 1",
    kind: "reporter",
    fields: [field("port", "dropdown", "1", { values: PORTS })],
    runtimeStatus: "stub",
    generatorHandlerId: "ai.imageRecognition",
    runtimeHandlerId: "runtime.diagnostic.aiNotImplemented",
    irV2Op: "ai.imageRecognition",
  }),
  entry({
    type: "ai_recognition_is",
    category: "AI",
    displayText: "recognition [input] is Number 0",
    kind: "boolean",
    fields: [
      field("input", "value-input", null, { required: true }),
      field("classType", "dropdown", "Number", { values: ["Number"] }),
      field("classValue", "text", "0"),
    ],
    runtimeStatus: "stub",
    generatorHandlerId: "ai.recognitionIs",
    runtimeHandlerId: "runtime.diagnostic.aiNotImplemented",
    irV2Op: "ai.recognitionMatches",
  }),
  entry({
    type: "c_code_function",
    category: "C Code",
    displayText: "void _fn(int _number1) { ... }",
    kind: "custom-code",
    fields: [
      field("functionName", "text", "_fn", { required: true }),
      field("parameterName", "text", "_number1"),
      field("arg", "value-input", 0),
      field("body", "textarea", "return _number1 + 1;", { required: true }),
    ],
    runtimeStatus: "blocked-by-sandbox",
    generatorHandlerId: "cCode.functionDefinition",
    runtimeHandlerId: "runtime.cSandbox.call",
    irV2Op: "cCode.call",
    notes: "Security-class: uses the C sandbox adapter and remains disabled unless the runtime feature flag is enabled.",
  }),
] as const satisfies readonly BlockRegistryEntry[];

export const BLOCK_REGISTRY_BY_TYPE = Object.fromEntries(
  WHALESBOT_BLOCK_REGISTRY.map((block) => [block.type, block]),
) as Record<(typeof WHALESBOT_BLOCK_REGISTRY)[number]["type"], (typeof WHALESBOT_BLOCK_REGISTRY)[number]>;

export const BLOCK_REGISTRY_BY_CATEGORY = BLOCK_CATEGORIES.reduce(
  (acc, category) => {
    acc[category] = WHALESBOT_BLOCK_REGISTRY.filter((block) => block.category === category);
    return acc;
  },
  {} as Record<BlockCategory, readonly BlockRegistryEntry[]>,
);

export const DOCUMENTED_BLOCK_COUNT = WHALESBOT_BLOCK_REGISTRY.length;
