import { PORTS } from "../constants.js";
import { entry, field, noFields } from "../helpers.js";

export const lightSpeakerEntries = [
  entry({
    type: "light_play_sound",
    category: "Light Speaker",
    displayText: "play sound Greet Hello",
    kind: "statement",
    fields: [
      field("group", "dropdown", "Greet", { values: ["Greet", "Effect", "Animal", "Music"] }),
      field("sound", "dropdown", "Hello", { values: ["Hello"] }),
    ],
    runtimeStatus: "telemetry-only",
    generatorHandlerId: "lightSpeaker.playSound",
    runtimeHandlerId: "runtime.telemetry.sound",
    irV2Op: "effect.playSound",
  }),
  entry({
    type: "light_electromagnet",
    category: "Light Speaker",
    displayText: "electromagnet port 1 absorption",
    kind: "statement",
    fields: [
      field("port", "dropdown", "1", { values: PORTS }),
      field("mode", "dropdown", "absorption", { values: ["absorption", "release"] }),
    ],
    runtimeStatus: "telemetry-only",
    generatorHandlerId: "lightSpeaker.electromagnet",
    runtimeHandlerId: "runtime.telemetry.electromagnet",
    irV2Op: "effect.electromagnet",
  }),
  entry({
    type: "light_emotion_expression",
    category: "Light Speaker",
    displayText: "emotion screen expression [eyes] left eye port 1 right eye port 2",
    kind: "statement",
    fields: [
      field("expression", "dropdown", "eyes", { values: ["eyes"] }),
      field("leftEyePort", "dropdown", "1", { values: PORTS }),
      field("rightEyePort", "dropdown", "2", { values: PORTS }),
    ],
    runtimeStatus: "telemetry-only",
    generatorHandlerId: "lightSpeaker.emotionExpression",
    runtimeHandlerId: "runtime.telemetry.display",
    irV2Op: "effect.emotionExpression",
  }),
  entry({
    type: "light_clear_emotion_expressions",
    category: "Light Speaker",
    displayText: "clear emotion screen expressions left eye port 1 right eye port 2",
    kind: "statement",
    fields: [
      field("leftEyePort", "dropdown", "1", { values: PORTS }),
      field("rightEyePort", "dropdown", "2", { values: PORTS }),
    ],
    runtimeStatus: "telemetry-only",
    generatorHandlerId: "lightSpeaker.clearEmotionExpressions",
    runtimeHandlerId: "runtime.telemetry.display",
    irV2Op: "effect.clearEmotionExpressions",
  }),
  entry({
    type: "light_emotion_symbols",
    category: "Light Speaker",
    displayText: "emotion screen symbols [?] port 1",
    kind: "statement",
    fields: [
      field("symbol", "dropdown", "?", { values: ["?", "!", "heart", "smile"] }),
      field("port", "dropdown", "1", { values: PORTS }),
    ],
    runtimeStatus: "telemetry-only",
    generatorHandlerId: "lightSpeaker.emotionSymbols",
    runtimeHandlerId: "runtime.telemetry.display",
    irV2Op: "effect.emotionSymbol",
  }),
  entry({
    type: "light_emotion_customization",
    category: "Light Speaker",
    displayText: "emotion screen customization [matrix] port 1",
    kind: "statement",
    fields: [
      field("matrix", "matrix", null),
      field("port", "dropdown", "1", { values: PORTS }),
    ],
    runtimeStatus: "telemetry-only",
    generatorHandlerId: "lightSpeaker.emotionCustomization",
    runtimeHandlerId: "runtime.telemetry.display",
    irV2Op: "effect.emotionMatrix",
  }),
  entry({
    type: "light_clear_emotion_screen",
    category: "Light Speaker",
    displayText: "clear emotion screen port 1",
    kind: "statement",
    fields: [field("port", "dropdown", "1", { values: PORTS })],
    runtimeStatus: "telemetry-only",
    generatorHandlerId: "lightSpeaker.clearEmotionScreen",
    runtimeHandlerId: "runtime.telemetry.display",
    irV2Op: "effect.clearEmotionScreen",
  }),
  entry({
    type: "light_reading_1",
    category: "Light Speaker",
    displayText: "reading 1",
    kind: "statement",
    fields: [field("value", "number", 1)],
    runtimeStatus: "stub",
    generatorHandlerId: "compat.reading1",
    runtimeHandlerId: "runtime.diagnostic.intentionalNoop",
    irV2Op: "compat.reading1",
    notes: "Intentional compatibility stub from doc section 15.",
  }),
  entry({
    type: "light_led_rgb",
    category: "Light Speaker",
    displayText: "set LED lights port 1 color R 255 G 255 B 255",
    kind: "statement",
    fields: [
      field("port", "dropdown", "1", { values: PORTS }),
      field("r", "number", 255, { min: 0, max: 255 }),
      field("g", "number", 255, { min: 0, max: 255 }),
      field("b", "number", 255, { min: 0, max: 255 }),
    ],
    runtimeStatus: "telemetry-only",
    generatorHandlerId: "lightSpeaker.ledRgb",
    runtimeHandlerId: "runtime.telemetry.led",
    irV2Op: "effect.setLedRgb",
  }),
  entry({
    type: "light_led_swatch",
    category: "Light Speaker",
    displayText: "set LED lights port 1 color [swatch]",
    kind: "statement",
    fields: [
      field("port", "dropdown", "1", { values: PORTS }),
      field("color", "color", "#ffffff"),
    ],
    runtimeStatus: "telemetry-only",
    generatorHandlerId: "lightSpeaker.ledSwatch",
    runtimeHandlerId: "runtime.telemetry.led",
    irV2Op: "effect.setLedColor",
  }),
  entry({
    type: "light_led_off",
    category: "Light Speaker",
    displayText: "turn off LED port 1",
    kind: "statement",
    fields: [field("port", "dropdown", "1", { values: PORTS })],
    runtimeStatus: "telemetry-only",
    generatorHandlerId: "lightSpeaker.ledOff",
    runtimeHandlerId: "runtime.telemetry.led",
    irV2Op: "effect.turnOffLed",
  }),
  entry({
    type: "light_digital_tube_display",
    category: "Light Speaker",
    displayText: "digital tube port 1 [value]",
    kind: "statement",
    fields: [
      field("port", "dropdown", "1", { values: PORTS }),
      field("value", "value-input", 0),
    ],
    runtimeStatus: "telemetry-only",
    generatorHandlerId: "lightSpeaker.digitalTubeDisplay",
    runtimeHandlerId: "runtime.telemetry.display",
    irV2Op: "effect.digitalTubeDisplay",
  }),
  entry({
    type: "light_clear_digital_tube",
    category: "Light Speaker",
    displayText: "clear digital tube port 1",
    kind: "statement",
    fields: [field("port", "dropdown", "1", { values: PORTS })],
    runtimeStatus: "telemetry-only",
    generatorHandlerId: "lightSpeaker.clearDigitalTube",
    runtimeHandlerId: "runtime.telemetry.display",
    irV2Op: "effect.clearDigitalTube",
  }),
  entry({
    type: "light_screen_display",
    category: "Light Speaker",
    displayText: "screen display [value]",
    kind: "statement",
    fields: [field("value", "value-input", "")],
    runtimeStatus: "telemetry-only",
    generatorHandlerId: "lightSpeaker.screenDisplay",
    runtimeHandlerId: "runtime.telemetry.display",
    irV2Op: "effect.screenDisplay",
  }),
  entry({
    type: "light_clear_screen",
    category: "Light Speaker",
    displayText: "clear screen",
    kind: "statement",
    fields: noFields,
    runtimeStatus: "telemetry-only",
    generatorHandlerId: "lightSpeaker.clearScreen",
    runtimeHandlerId: "runtime.telemetry.display",
    irV2Op: "effect.clearScreen",
  }),
];
