import { entry, field } from "../helpers.js";

export const logicEntries = [
  entry({
    type: "logic_if_then",
    category: "Logic",
    displayText: "if [condition] then",
    kind: "c-block",
    fields: [
      field("condition", "boolean-input", null, { required: true }),
      field("then", "statement-input", null),
    ],
    runtimeStatus: "stub",
    generatorHandlerId: "logic.ifThen",
    runtimeHandlerId: "runtime.diagnostic.booleanFlowNotImplemented",
    irV2Op: "control.if",
  }),
  entry({
    type: "logic_if_then_else",
    category: "Logic",
    displayText: "if [condition] then else",
    kind: "c-block",
    fields: [
      field("condition", "boolean-input", null, { required: true }),
      field("then", "statement-input", null),
      field("else", "statement-input", null),
    ],
    runtimeStatus: "stub",
    generatorHandlerId: "logic.ifThenElse",
    runtimeHandlerId: "runtime.diagnostic.booleanFlowNotImplemented",
    irV2Op: "control.ifElse",
  }),
  entry({
    type: "logic_compare_lt",
    category: "Logic",
    displayText: "[a] < [b]",
    kind: "boolean",
    fields: [field("a", "value-input", null), field("b", "value-input", null)],
    runtimeStatus: "stub",
    generatorHandlerId: "logic.compareLt",
    runtimeHandlerId: "runtime.diagnostic.expressionsNotImplemented",
    irV2Op: "boolean.compare",
  }),
  entry({
    type: "logic_compare_gt",
    category: "Logic",
    displayText: "[a] > [b]",
    kind: "boolean",
    fields: [field("a", "value-input", null), field("b", "value-input", null)],
    runtimeStatus: "stub",
    generatorHandlerId: "logic.compareGt",
    runtimeHandlerId: "runtime.diagnostic.expressionsNotImplemented",
    irV2Op: "boolean.compare",
  }),
  entry({
    type: "logic_compare_eq",
    category: "Logic",
    displayText: "[a] = [b]",
    kind: "boolean",
    fields: [field("a", "value-input", null), field("b", "value-input", null)],
    runtimeStatus: "stub",
    generatorHandlerId: "logic.compareEq",
    runtimeHandlerId: "runtime.diagnostic.expressionsNotImplemented",
    irV2Op: "boolean.compare",
  }),
  entry({
    type: "logic_compare_neq",
    category: "Logic",
    displayText: "[a] not equal [b]",
    kind: "boolean",
    fields: [field("a", "value-input", null), field("b", "value-input", null)],
    runtimeStatus: "stub",
    generatorHandlerId: "logic.compareNeq",
    runtimeHandlerId: "runtime.diagnostic.expressionsNotImplemented",
    irV2Op: "boolean.compare",
  }),
  entry({
    type: "logic_and",
    category: "Logic",
    displayText: "[cond1] and [cond2]",
    kind: "boolean",
    fields: [field("cond1", "boolean-input", null), field("cond2", "boolean-input", null)],
    runtimeStatus: "stub",
    generatorHandlerId: "logic.and",
    runtimeHandlerId: "runtime.diagnostic.expressionsNotImplemented",
    irV2Op: "boolean.and",
  }),
  entry({
    type: "logic_or",
    category: "Logic",
    displayText: "[cond1] or [cond2]",
    kind: "boolean",
    fields: [field("cond1", "boolean-input", null), field("cond2", "boolean-input", null)],
    runtimeStatus: "stub",
    generatorHandlerId: "logic.or",
    runtimeHandlerId: "runtime.diagnostic.expressionsNotImplemented",
    irV2Op: "boolean.or",
  }),
  entry({
    type: "logic_not",
    category: "Logic",
    displayText: "not [condition]",
    kind: "boolean",
    fields: [field("condition", "boolean-input", null)],
    runtimeStatus: "stub",
    generatorHandlerId: "logic.not",
    runtimeHandlerId: "runtime.diagnostic.expressionsNotImplemented",
    irV2Op: "boolean.not",
  }),
];
