import { entry, field, noFields } from "../helpers.js";

export const loopEntries = [
  entry({
    type: "loop_repeat_forever",
    category: "Loop",
    displayText: "repeat forever",
    kind: "c-block",
    fields: [field("do", "statement-input", null)],
    runtimeStatus: "implemented",
    generatorHandlerId: "loop.repeatForever",
    runtimeHandlerId: "runtime.control.repeatForever",
    irV2Op: "control.repeatForever",
  }),
  entry({
    type: "loop_repeat_times",
    category: "Loop",
    displayText: "repeat 10 times",
    kind: "c-block",
    fields: [
      field("times", "number", 10, { min: 0 }),
      field("do", "statement-input", null),
    ],
    runtimeStatus: "implemented",
    generatorHandlerId: "loop.repeatTimes",
    runtimeHandlerId: "runtime.control.repeatTimes",
    irV2Op: "control.repeatTimes",
  }),
  entry({
    type: "loop_while_condition",
    category: "Loop",
    displayText: "if [condition] repeat",
    kind: "c-block",
    fields: [
      field("condition", "boolean-input", null, { required: true }),
      field("do", "statement-input", null),
    ],
    runtimeStatus: "stub",
    generatorHandlerId: "loop.whileCondition",
    runtimeHandlerId: "runtime.diagnostic.booleanFlowNotImplemented",
    irV2Op: "control.while",
  }),
  entry({
    type: "loop_repeat_until",
    category: "Loop",
    displayText: "repeat until [condition]",
    kind: "c-block",
    fields: [
      field("condition", "boolean-input", null, { required: true }),
      field("do", "statement-input", null),
    ],
    runtimeStatus: "stub",
    generatorHandlerId: "loop.repeatUntil",
    runtimeHandlerId: "runtime.diagnostic.booleanFlowNotImplemented",
    irV2Op: "control.repeatUntil",
  }),
  entry({
    type: "loop_break",
    category: "Loop",
    displayText: "break",
    kind: "statement",
    fields: noFields,
    runtimeStatus: "stub",
    generatorHandlerId: "loop.break",
    runtimeHandlerId: "runtime.diagnostic.loopBreakNotImplemented",
    irV2Op: "control.break",
  }),
  entry({
    type: "loop_return_value",
    category: "Loop",
    displayText: "Return [value]",
    kind: "statement",
    fields: [field("value", "value-input", null)],
    runtimeStatus: "stub",
    generatorHandlerId: "loop.returnValue",
    runtimeHandlerId: "runtime.diagnostic.functionsNotImplemented",
    irV2Op: "control.return",
  }),
  entry({
    type: "loop_wait_seconds",
    category: "Loop",
    displayText: "wait 2 secs.",
    kind: "statement",
    fields: [field("seconds", "number", 2, { min: 0, unit: "seconds" })],
    runtimeStatus: "implemented",
    generatorHandlerId: "loop.waitSeconds",
    runtimeHandlerId: "runtime.control.waitTicks",
    irV2Op: "control.waitSeconds",
  }),
  entry({
    type: "loop_wait_until",
    category: "Loop",
    displayText: "wait until [condition]",
    kind: "statement",
    fields: [field("condition", "boolean-input", null, { required: true })],
    runtimeStatus: "stub",
    generatorHandlerId: "loop.waitUntil",
    runtimeHandlerId: "runtime.diagnostic.booleanFlowNotImplemented",
    irV2Op: "control.waitUntil",
  }),
];
