import { ANGLE_UNITS, MATH_UNARY_OPS } from "../constants.js";
import { entry, field } from "../helpers.js";

export const mathEntries = [
  entry({
    type: "math_add",
    category: "Math",
    displayText: "[10] + [10]",
    kind: "reporter-number",
    fields: [field("left", "value-input", 10), field("right", "value-input", 10)],
    runtimeStatus: "stub",
    generatorHandlerId: "math.add",
    runtimeHandlerId: "runtime.diagnostic.expressionsNotImplemented",
    irV2Op: "value.binary",
  }),
  entry({
    type: "math_subtract",
    category: "Math",
    displayText: "[10] - [10]",
    kind: "reporter-number",
    fields: [field("left", "value-input", 10), field("right", "value-input", 10)],
    runtimeStatus: "stub",
    generatorHandlerId: "math.subtract",
    runtimeHandlerId: "runtime.diagnostic.expressionsNotImplemented",
    irV2Op: "value.binary",
  }),
  entry({
    type: "math_multiply",
    category: "Math",
    displayText: "[10] x [10]",
    kind: "reporter-number",
    fields: [field("left", "value-input", 10), field("right", "value-input", 10)],
    runtimeStatus: "stub",
    generatorHandlerId: "math.multiply",
    runtimeHandlerId: "runtime.diagnostic.expressionsNotImplemented",
    irV2Op: "value.binary",
  }),
  entry({
    type: "math_divide",
    category: "Math",
    displayText: "[10] / [10]",
    kind: "reporter-number",
    fields: [field("left", "value-input", 10), field("right", "value-input", 10)],
    runtimeStatus: "stub",
    generatorHandlerId: "math.divide",
    runtimeHandlerId: "runtime.diagnostic.expressionsNotImplemented",
    irV2Op: "value.binary",
  }),
  entry({
    type: "math_random_range",
    category: "Math",
    displayText: "pick random from 0 to 10",
    kind: "reporter-number",
    fields: [field("min", "number", 0), field("max", "number", 10)],
    runtimeStatus: "stub",
    generatorHandlerId: "math.randomRange",
    runtimeHandlerId: "runtime.diagnostic.expressionsNotImplemented",
    irV2Op: "value.randomRange",
  }),
  entry({
    type: "math_modulo",
    category: "Math",
    displayText: "the remainder of dividing [a] by [b]",
    kind: "reporter-number",
    fields: [field("a", "value-input", null), field("b", "value-input", null)],
    runtimeStatus: "stub",
    generatorHandlerId: "math.modulo",
    runtimeHandlerId: "runtime.diagnostic.expressionsNotImplemented",
    irV2Op: "value.modulo",
  }),
  entry({
    type: "math_round",
    category: "Math",
    displayText: "round [x]",
    kind: "reporter-number",
    fields: [field("value", "value-input", null)],
    runtimeStatus: "stub",
    generatorHandlerId: "math.round",
    runtimeHandlerId: "runtime.diagnostic.expressionsNotImplemented",
    irV2Op: "value.round",
  }),
  entry({
    type: "math_unary_function",
    category: "Math",
    displayText: "abs [x]",
    kind: "reporter-number",
    fields: [
      field("op", "dropdown", "abs", { values: MATH_UNARY_OPS }),
      field("value", "value-input", null),
      field("angleUnit", "dropdown", "degree", { values: ANGLE_UNITS }),
    ],
    runtimeStatus: "stub",
    generatorHandlerId: "math.unaryFunction",
    runtimeHandlerId: "runtime.diagnostic.expressionsNotImplemented",
    irV2Op: "value.unary",
    notes: "Trig and inverse trig carry explicit degree/radian units.",
  }),
];
