import { MOTOR_PORTS, MOTOR_PORTS_WITH_ALL, DIRECTIONS, TURN_DIRECTIONS, STEERING_IDS } from "../constants.js";
import { entry, field, noFields } from "../helpers.js";

export const motionEntries = [
  entry({
    type: "motion_tank_drive_continuous",
    category: "Motion",
    displayText: "move left motor A right motor B Forward power 40 %",
    kind: "statement",
    fields: [
      field("leftMotor", "dropdown", "A", { values: MOTOR_PORTS }),
      field("rightMotor", "dropdown", "B", { values: MOTOR_PORTS }),
      field("direction", "dropdown", "Forward", { values: DIRECTIONS }),
      field("power", "number", 40, { min: -100, max: 100, unit: "percent" }),
    ],
    runtimeStatus: "implemented",
    generatorHandlerId: "motion.tankDriveContinuous",
    runtimeHandlerId: "runtime.motor.setPair",
    irV2Op: "motion.setMotorPair",
  }),
  entry({
    type: "motion_tank_drive_seconds",
    category: "Motion",
    displayText: "move left motor A right motor B Forward power 40 % run for 1 secs.",
    kind: "statement",
    fields: [
      field("leftMotor", "dropdown", "A", { values: MOTOR_PORTS }),
      field("rightMotor", "dropdown", "B", { values: MOTOR_PORTS }),
      field("direction", "dropdown", "Forward", { values: DIRECTIONS }),
      field("power", "number", 40, { min: -100, max: 100, unit: "percent" }),
      field("seconds", "number", 1, { min: 0, unit: "seconds" }),
    ],
    runtimeStatus: "implemented",
    generatorHandlerId: "motion.tankDriveSeconds",
    runtimeHandlerId: "runtime.motor.setPairForTime",
    irV2Op: "motion.setMotorPairForTime",
  }),
  entry({
    type: "motion_stop_pair",
    category: "Motion",
    displayText: "stop left motor A right motor B",
    kind: "statement",
    fields: [
      field("leftMotor", "dropdown", "A", { values: MOTOR_PORTS }),
      field("rightMotor", "dropdown", "B", { values: MOTOR_PORTS }),
    ],
    runtimeStatus: "implemented",
    generatorHandlerId: "motion.stopPair",
    runtimeHandlerId: "runtime.motor.stopPair",
    irV2Op: "motion.stopMotorPair",
  }),
  entry({
    type: "motion_single_motor_power",
    category: "Motion",
    displayText: "set motor A power 40 %",
    kind: "statement",
    fields: [
      field("motor", "dropdown", "A", { values: MOTOR_PORTS }),
      field("power", "number", 40, { min: -100, max: 100, unit: "percent" }),
    ],
    runtimeStatus: "implemented",
    generatorHandlerId: "motion.singleMotorPower",
    runtimeHandlerId: "runtime.motor.setSingle",
    irV2Op: "motion.setMotor",
  }),
  entry({
    type: "motion_dual_motor_seconds",
    category: "Motion",
    displayText: "set motor A power 40 % motor B power 40 % run for 1 secs.",
    kind: "statement",
    fields: [
      field("motorA", "dropdown", "A", { values: MOTOR_PORTS }),
      field("powerA", "number", 40, { min: -100, max: 100, unit: "percent" }),
      field("motorB", "dropdown", "B", { values: MOTOR_PORTS }),
      field("powerB", "number", 40, { min: -100, max: 100, unit: "percent" }),
      field("seconds", "number", 1, { min: 0, unit: "seconds" }),
    ],
    runtimeStatus: "implemented",
    generatorHandlerId: "motion.dualMotorSeconds",
    runtimeHandlerId: "runtime.motor.setPairForTime",
    irV2Op: "motion.setMotorPairForTime",
  }),
  entry({
    type: "motion_single_motor_seconds",
    category: "Motion",
    displayText: "set motor A power 40 % run for 1 secs.",
    kind: "statement",
    fields: [
      field("motor", "dropdown", "A", { values: MOTOR_PORTS }),
      field("power", "number", 40, { min: -100, max: 100, unit: "percent" }),
      field("seconds", "number", 1, { min: 0, unit: "seconds" }),
    ],
    runtimeStatus: "implemented",
    generatorHandlerId: "motion.singleMotorSeconds",
    runtimeHandlerId: "runtime.motor.setSingleForTime",
    irV2Op: "motion.setMotorForTime",
  }),
  entry({
    type: "motion_dual_motor_degrees",
    category: "Motion",
    displayText: "set motor A power 40 % motor B power 40 % rotate for 360 degrees",
    kind: "statement",
    fields: [
      field("motorA", "dropdown", "A", { values: MOTOR_PORTS }),
      field("powerA", "number", 40, { min: -100, max: 100, unit: "percent" }),
      field("motorB", "dropdown", "B", { values: MOTOR_PORTS }),
      field("powerB", "number", 40, { min: -100, max: 100, unit: "percent" }),
      field("degrees", "number", 360, { unit: "encoder degrees" }),
    ],
    runtimeStatus: "stub",
    generatorHandlerId: "motion.dualMotorDegrees",
    runtimeHandlerId: "runtime.diagnostic.encoderNotImplemented",
    irV2Op: "motion.setMotorPairForEncoderDegrees",
  }),
  entry({
    type: "motion_single_motor_degrees",
    category: "Motion",
    displayText: "set motor A power 40 % rotate for 360 degrees",
    kind: "statement",
    fields: [
      field("motor", "dropdown", "A", { values: MOTOR_PORTS }),
      field("power", "number", 40, { min: -100, max: 100, unit: "percent" }),
      field("degrees", "number", 360, { unit: "encoder degrees" }),
    ],
    runtimeStatus: "stub",
    generatorHandlerId: "motion.singleMotorDegrees",
    runtimeHandlerId: "runtime.diagnostic.encoderNotImplemented",
    irV2Op: "motion.setMotorForEncoderDegrees",
  }),
  entry({
    type: "motion_reverse_motor",
    category: "Motion",
    displayText: "reverse motor A",
    kind: "statement",
    fields: [field("motor", "dropdown", "A", { values: MOTOR_PORTS })],
    runtimeStatus: "implemented",
    generatorHandlerId: "motion.reverseMotor",
    runtimeHandlerId: "runtime.motor.reverse",
    irV2Op: "motion.reverseMotor",
  }),
  entry({
    type: "motion_stop_motor",
    category: "Motion",
    displayText: "stop motor all",
    kind: "statement",
    fields: [field("motor", "dropdown", "all", { values: MOTOR_PORTS_WITH_ALL })],
    runtimeStatus: "implemented",
    generatorHandlerId: "motion.stopMotor",
    runtimeHandlerId: "runtime.motor.stop",
    irV2Op: "motion.stopMotor",
  }),
  entry({
    type: "motion_omni_move",
    category: "Motion",
    displayText: "omni-wheel move power 40 % towards 0 degree",
    kind: "statement",
    fields: [
      field("power", "number", 40, { min: -100, max: 100, unit: "percent" }),
      field("headingDegrees", "number", 0, { unit: "degrees" }),
    ],
    runtimeStatus: "stub",
    generatorHandlerId: "motion.omniMove",
    runtimeHandlerId: "runtime.diagnostic.omniDriveNotImplemented",
    irV2Op: "motion.omniMove",
  }),
  entry({
    type: "motion_omni_turn",
    category: "Motion",
    displayText: "omni-wheel turn Turn left power 40 %",
    kind: "statement",
    fields: [
      field("direction", "dropdown", "Turn left", { values: TURN_DIRECTIONS }),
      field("power", "number", 40, { min: -100, max: 100, unit: "percent" }),
    ],
    runtimeStatus: "stub",
    generatorHandlerId: "motion.omniTurn",
    runtimeHandlerId: "runtime.diagnostic.omniDriveNotImplemented",
    irV2Op: "motion.omniTurn",
  }),
  entry({
    type: "motion_omni_stop",
    category: "Motion",
    displayText: "stop omni-wheel move",
    kind: "statement",
    fields: noFields,
    runtimeStatus: "stub",
    generatorHandlerId: "motion.omniStop",
    runtimeHandlerId: "runtime.diagnostic.omniDriveNotImplemented",
    irV2Op: "motion.omniStop",
  }),
  entry({
    type: "motion_steering_angle_mode",
    category: "Motion",
    displayText: "set up steering gear angle mode ID 1 speed 40 angle 0",
    kind: "statement",
    fields: [
      field("id", "dropdown", "1", { values: STEERING_IDS }),
      field("speed", "number", 40, { min: 0, max: 100 }),
      field("angle", "number", 0, { unit: "degrees" }),
    ],
    runtimeStatus: "telemetry-only",
    generatorHandlerId: "motion.steeringAngleMode",
    runtimeHandlerId: "runtime.telemetry.steeringGear",
    irV2Op: "motion.steeringGearAngle",
  }),
  entry({
    type: "motion_steering_rotation_mode",
    category: "Motion",
    displayText: "set up steering gear rotation mode ID 1 speed 40",
    kind: "statement",
    fields: [
      field("id", "dropdown", "1", { values: STEERING_IDS }),
      field("speed", "number", 40, { min: -100, max: 100 }),
    ],
    runtimeStatus: "telemetry-only",
    generatorHandlerId: "motion.steeringRotationMode",
    runtimeHandlerId: "runtime.telemetry.steeringGear",
    irV2Op: "motion.steeringGearRotation",
  }),
  entry({
    type: "motion_restore_steering_torque",
    category: "Motion",
    displayText: "restore steering torque",
    kind: "statement",
    fields: noFields,
    runtimeStatus: "telemetry-only",
    generatorHandlerId: "motion.restoreSteeringTorque",
    runtimeHandlerId: "runtime.telemetry.steeringGear",
    irV2Op: "motion.restoreSteeringTorque",
  }),
];
