import { MOTOR_PORTS, PORTS, PATROL_INTERSECTION_BRANCHES, PATROL_TURN_BRANCHES, COMPARE_OPS } from "../constants.js";
import { entry, field, noFields } from "../helpers.js";

export const patrolEntries = [
  entry({
    type: "patrol_initialize_tank",
    category: "Patrol line",
    displayText: "initialize left motor A 100 right motor B -100 integrated grayscale port 5",
    kind: "statement",
    fields: [
      field("leftMotor", "dropdown", "A", { values: MOTOR_PORTS }),
      field("leftDirection", "number", 100),
      field("rightMotor", "dropdown", "B", { values: MOTOR_PORTS }),
      field("rightDirection", "number", -100),
      field("grayscalePort", "dropdown", "5", { values: PORTS }),
    ],
    runtimeStatus: "implemented",
    generatorHandlerId: "patrol.initializeTank",
    runtimeHandlerId: "runtime.hardware.initializeTank",
    irV2Op: "hardware.initializeTankLineFollower",
  }),
  entry({
    type: "patrol_initialize_omni",
    category: "Patrol line",
    displayText: "initialize omni-wheel Left front motorA 100 Right front motorB 100 Right rear motorC 100 Left rear motorD 100 integrated grayscale port 5",
    kind: "statement",
    fields: [
      field("leftFrontMotor", "dropdown", "A", { values: MOTOR_PORTS }),
      field("rightFrontMotor", "dropdown", "B", { values: MOTOR_PORTS }),
      field("rightRearMotor", "dropdown", "C", { values: MOTOR_PORTS }),
      field("leftRearMotor", "dropdown", "D", { values: MOTOR_PORTS }),
      field("leftFrontDirection", "number", 100),
      field("rightFrontDirection", "number", 100),
      field("rightRearDirection", "number", 100),
      field("leftRearDirection", "number", 100),
      field("grayscalePort", "dropdown", "5", { values: PORTS }),
    ],
    runtimeStatus: "stub",
    generatorHandlerId: "patrol.initializeOmni",
    runtimeHandlerId: "runtime.diagnostic.omniDriveNotImplemented",
    irV2Op: "hardware.initializeOmniLineFollower",
  }),
  entry({
    type: "patrol_black_white_detection",
    category: "Patrol line",
    displayText: "black and white detection",
    kind: "statement",
    fields: noFields,
    runtimeStatus: "implemented",
    generatorHandlerId: "patrol.blackWhiteDetection",
    runtimeHandlerId: "runtime.sensor.calibrateGrayscale",
    irV2Op: "sensor.calibrateGrayscale",
  }),
  entry({
    type: "patrol_line_speed",
    category: "Patrol line",
    displayText: "patrol line speed 30",
    kind: "statement",
    fields: [field("speed", "number", 30, { min: 0, max: 100 })],
    runtimeStatus: "implemented",
    generatorHandlerId: "patrol.lineSpeed",
    runtimeHandlerId: "runtime.lineFollower.continuous",
    irV2Op: "lineFollower.followContinuous",
  }),
  entry({
    type: "patrol_line_for_time",
    category: "Patrol line",
    displayText: "patrol line patrol line speed 30 for 0.5",
    kind: "statement",
    fields: [
      field("speed", "number", 30, { min: 0, max: 100 }),
      field("seconds", "number", 0.5, { min: 0, unit: "seconds" }),
    ],
    runtimeStatus: "implemented",
    generatorHandlerId: "patrol.lineForTime",
    runtimeHandlerId: "runtime.lineFollower.forTime",
    irV2Op: "lineFollower.followForTime",
  }),
  entry({
    type: "patrol_line_intersections",
    category: "Patrol line",
    displayText: "patrol line intersections left patrol line speed 30 rush through intersection time 0",
    kind: "statement",
    fields: [
      field("branch", "dropdown", "left", { values: PATROL_INTERSECTION_BRANCHES }),
      field("speed", "number", 30, { min: 0, max: 100 }),
      field("rushSeconds", "number", 0, { min: 0, unit: "seconds" }),
    ],
    runtimeStatus: "implemented",
    generatorHandlerId: "patrol.lineUntilIntersection",
    runtimeHandlerId: "runtime.lineFollower.untilIntersection",
    irV2Op: "lineFollower.untilIntersection",
  }),
  entry({
    type: "patrol_turn_branch",
    category: "Patrol line",
    displayText: "turn middle left motor speed 0 right motor speed 0",
    kind: "statement",
    fields: [
      field("branch", "dropdown", "middle", { values: PATROL_TURN_BRANCHES }),
      field("leftSpeed", "number", 0, { min: -100, max: 100 }),
      field("rightSpeed", "number", 0, { min: -100, max: 100 }),
    ],
    runtimeStatus: "implemented",
    generatorHandlerId: "patrol.turnBranch",
    runtimeHandlerId: "runtime.lineFollower.turnUntilBranch",
    irV2Op: "lineFollower.turnUntilBranch",
  }),
  entry({
    type: "patrol_start_motor_time",
    category: "Patrol line",
    displayText: "start motor left motor speed 20 right motor speed 20 time 0.5",
    kind: "statement",
    fields: [
      field("leftSpeed", "number", 20, { min: -100, max: 100 }),
      field("rightSpeed", "number", 20, { min: -100, max: 100 }),
      field("seconds", "number", 0.5, { min: 0, unit: "seconds" }),
    ],
    runtimeStatus: "implemented",
    generatorHandlerId: "patrol.startMotorTime",
    runtimeHandlerId: "runtime.motor.setPairForTime",
    irV2Op: "motion.setMotorPairForTime",
  }),
  entry({
    type: "patrol_start_motor_angle",
    category: "Patrol line",
    displayText: "start motor left motor speed 20 right motor speed 20 angle 360",
    kind: "statement",
    fields: [
      field("leftSpeed", "number", 20, { min: -100, max: 100 }),
      field("rightSpeed", "number", 20, { min: -100, max: 100 }),
      field("degrees", "number", 360, { unit: "encoder degrees" }),
    ],
    runtimeStatus: "stub",
    generatorHandlerId: "patrol.startMotorAngle",
    runtimeHandlerId: "runtime.diagnostic.encoderNotImplemented",
    irV2Op: "motion.setMotorPairForEncoderDegrees",
  }),
  entry({
    type: "patrol_start_motor_until_sensor",
    category: "Patrol line",
    displayText: "start motor left motor speed 20 right motor speed 20 Sensor 1 < 50",
    kind: "statement",
    fields: [
      field("leftSpeed", "number", 20, { min: -100, max: 100 }),
      field("rightSpeed", "number", 20, { min: -100, max: 100 }),
      field("sensor", "dropdown", "1", { values: PORTS }),
      field("compare", "dropdown", "<", { values: COMPARE_OPS }),
      field("threshold", "number", 50),
    ],
    runtimeStatus: "implemented",
    generatorHandlerId: "patrol.startMotorUntilSensor",
    runtimeHandlerId: "runtime.motor.setPairUntil",
    irV2Op: "motion.setMotorPairUntil",
  }),
  entry({
    type: "patrol_start_button",
    category: "Patrol line",
    displayText: "start button",
    kind: "statement",
    fields: noFields,
    runtimeStatus: "stub",
    generatorHandlerId: "compat.startButton",
    runtimeHandlerId: "runtime.diagnostic.intentionalNoop",
    irV2Op: "compat.startButton",
    notes: "Intentional compatibility stub from doc section 15.",
  }),
];
