import { PORTS, MOTOR_PORTS, GRAYSCALE_DETECTED_VALUES, COLORS } from "../constants.js";
import { entry, field, noFields } from "../helpers.js";

export const sensorEntries = [
  entry({
    type: "sensor_touch_switch_pressed",
    category: "Sensor",
    displayText: "touch switch 1 pressed",
    kind: "boolean",
    fields: [field("port", "dropdown", "1", { values: PORTS })],
    runtimeStatus: "stub",
    generatorHandlerId: "sensor.touchSwitchPressed",
    runtimeHandlerId: "runtime.diagnostic.sensorNotImplemented",
    irV2Op: "sensor.touchSwitchPressed",
  }),
  entry({
    type: "sensor_infrared_obstacle",
    category: "Sensor",
    displayText: "infrared port 1 obstacles detected",
    kind: "boolean",
    fields: [field("port", "dropdown", "1", { values: PORTS })],
    runtimeStatus: "stub",
    generatorHandlerId: "sensor.infraredObstacle",
    runtimeHandlerId: "runtime.diagnostic.sensorNotImplemented",
    irV2Op: "sensor.infraredObstacle",
  }),
  entry({
    type: "sensor_infrared_range_value",
    category: "Sensor",
    displayText: "infrared ranging sensor port 1 value",
    kind: "reporter-number",
    fields: [field("port", "dropdown", "1", { values: PORTS })],
    runtimeStatus: "stub",
    generatorHandlerId: "sensor.infraredRangeValue",
    runtimeHandlerId: "runtime.diagnostic.sensorNotImplemented",
    irV2Op: "sensor.infraredRange",
  }),
  entry({
    type: "sensor_integrated_grayscale_detect_black",
    category: "Sensor",
    displayText: "integrated grayscale port 5 channel 1 detected black",
    kind: "boolean",
    fields: [
      field("port", "dropdown", "5", { values: PORTS }),
      field("channel", "dropdown", "1", { values: PORTS }),
      field("color", "dropdown", "black", { values: GRAYSCALE_DETECTED_VALUES }),
    ],
    runtimeStatus: "implemented",
    generatorHandlerId: "sensor.integratedGrayscaleDetectBlack",
    runtimeHandlerId: "runtime.sensor.grayscaleDetectBlack",
    irV2Op: "sensor.grayscaleDetectBlack",
  }),
  entry({
    type: "sensor_integrated_grayscale_value",
    category: "Sensor",
    displayText: "integrated grayscale port 5 channel 1",
    kind: "reporter-number",
    fields: [
      field("port", "dropdown", "5", { values: PORTS }),
      field("channel", "dropdown", "1", { values: PORTS }),
    ],
    runtimeStatus: "implemented",
    generatorHandlerId: "sensor.integratedGrayscaleValue",
    runtimeHandlerId: "runtime.sensor.grayscaleValue",
    irV2Op: "sensor.grayscaleValue",
  }),
  entry({
    type: "sensor_single_grayscale_detect_black",
    category: "Sensor",
    displayText: "single grayscale port 1 detected black",
    kind: "boolean",
    fields: [
      field("port", "dropdown", "1", { values: PORTS }),
      field("color", "dropdown", "black", { values: GRAYSCALE_DETECTED_VALUES }),
    ],
    runtimeStatus: "implemented",
    generatorHandlerId: "sensor.singleGrayscaleDetectBlack",
    runtimeHandlerId: "runtime.sensor.singleGrayscaleDetectBlack",
    irV2Op: "sensor.singleGrayscaleDetectBlack",
  }),
  entry({
    type: "sensor_single_grayscale_value",
    category: "Sensor",
    displayText: "single grayscale port 1 detected value",
    kind: "reporter-number",
    fields: [field("port", "dropdown", "1", { values: PORTS })],
    runtimeStatus: "implemented",
    generatorHandlerId: "sensor.singleGrayscaleValue",
    runtimeHandlerId: "runtime.sensor.singleGrayscaleValue",
    irV2Op: "sensor.singleGrayscaleValue",
  }),
  entry({
    type: "sensor_ultrasonic_distance",
    category: "Sensor",
    displayText: "ultrasonic sensor port 1 detect distance cm",
    kind: "reporter-number",
    fields: [field("port", "dropdown", "1", { values: PORTS })],
    runtimeStatus: "stub",
    generatorHandlerId: "sensor.ultrasonicDistance",
    runtimeHandlerId: "runtime.diagnostic.sensorNotImplemented",
    irV2Op: "sensor.ultrasonicDistance",
  }),
  entry({
    type: "sensor_ambient_light_value",
    category: "Sensor",
    displayText: "ambient light port 1 value",
    kind: "reporter-number",
    fields: [field("port", "dropdown", "1", { values: PORTS })],
    runtimeStatus: "stub",
    generatorHandlerId: "sensor.ambientLightValue",
    runtimeHandlerId: "runtime.diagnostic.sensorNotImplemented",
    irV2Op: "sensor.ambientLight",
  }),
  entry({
    type: "sensor_temperature_celsius",
    category: "Sensor",
    displayText: "temperature sensor port 1 \u00b0C",
    kind: "reporter-number",
    fields: [field("port", "dropdown", "1", { values: PORTS })],
    runtimeStatus: "stub",
    generatorHandlerId: "sensor.temperatureCelsius",
    runtimeHandlerId: "runtime.diagnostic.sensorNotImplemented",
    irV2Op: "sensor.temperatureCelsius",
  }),
  entry({
    type: "sensor_humidity_percent",
    category: "Sensor",
    displayText: "humidity sensor port 1 value %",
    kind: "reporter-number",
    fields: [field("port", "dropdown", "1", { values: PORTS })],
    runtimeStatus: "stub",
    generatorHandlerId: "sensor.humidityPercent",
    runtimeHandlerId: "runtime.diagnostic.sensorNotImplemented",
    irV2Op: "sensor.humidityPercent",
  }),
  entry({
    type: "sensor_flame_value",
    category: "Sensor",
    displayText: "flame sensor port 1 value",
    kind: "reporter-number",
    fields: [field("port", "dropdown", "1", { values: PORTS })],
    runtimeStatus: "stub",
    generatorHandlerId: "sensor.flameValue",
    runtimeHandlerId: "runtime.diagnostic.sensorNotImplemented",
    irV2Op: "sensor.flameValue",
  }),
  entry({
    type: "sensor_magnetic_detected",
    category: "Sensor",
    displayText: "magnetic port 1 magnetic field detected",
    kind: "boolean",
    fields: [field("port", "dropdown", "1", { values: PORTS })],
    runtimeStatus: "stub",
    generatorHandlerId: "sensor.magneticDetected",
    runtimeHandlerId: "runtime.diagnostic.sensorNotImplemented",
    irV2Op: "sensor.magneticDetected",
  }),
  entry({
    type: "sensor_volume_detection",
    category: "Sensor",
    displayText: "volume detection port 1",
    kind: "reporter-number",
    fields: [field("port", "dropdown", "1", { values: PORTS })],
    runtimeStatus: "stub",
    generatorHandlerId: "sensor.volumeDetection",
    runtimeHandlerId: "runtime.diagnostic.sensorNotImplemented",
    irV2Op: "sensor.volumeDetection",
  }),
  entry({
    type: "sensor_motor_encoder_value",
    category: "Sensor",
    displayText: "motor encoder port A",
    kind: "reporter-number",
    fields: [field("motor", "dropdown", "A", { values: MOTOR_PORTS })],
    runtimeStatus: "implemented",
    generatorHandlerId: "sensor.motorEncoderValue",
    runtimeHandlerId: "runtime.sensor.motorEncoder",
    irV2Op: "sensor.motorEncoder",
  }),
  entry({
    type: "sensor_reset_motor_encoder",
    category: "Sensor",
    displayText: "reset motor encoder port A",
    kind: "statement",
    fields: [field("motor", "dropdown", "A", { values: MOTOR_PORTS })],
    runtimeStatus: "implemented",
    generatorHandlerId: "sensor.resetMotorEncoder",
    runtimeHandlerId: "runtime.sensor.resetMotorEncoder",
    irV2Op: "sensor.resetMotorEncoder",
  }),
  entry({
    type: "sensor_current_timer_value",
    category: "Sensor",
    displayText: "current timer value",
    kind: "reporter-number",
    fields: noFields,
    runtimeStatus: "implemented",
    generatorHandlerId: "sensor.currentTimerValue",
    runtimeHandlerId: "runtime.sensor.timerValue",
    irV2Op: "sensor.timerValue",
  }),
  entry({
    type: "sensor_reset_timer",
    category: "Sensor",
    displayText: "reset timer",
    kind: "statement",
    fields: noFields,
    runtimeStatus: "implemented",
    generatorHandlerId: "sensor.resetTimer",
    runtimeHandlerId: "runtime.sensor.resetTimer",
    irV2Op: "sensor.resetTimer",
  }),
  entry({
    type: "sensor_remote_control_button",
    category: "Sensor",
    displayText: "remote control button",
    kind: "reporter",
    fields: noFields,
    runtimeStatus: "stub",
    generatorHandlerId: "compat.remoteControlButton",
    runtimeHandlerId: "runtime.diagnostic.intentionalFalse",
    irV2Op: "compat.remoteControlButton",
    notes: "Intentional compatibility stub from doc section 15.",
  }),
  entry({
    type: "sensor_color_value",
    category: "Sensor",
    displayText: "Color sensor port 1",
    kind: "reporter",
    fields: [field("port", "dropdown", "1", { values: PORTS })],
    runtimeStatus: "stub",
    generatorHandlerId: "sensor.colorValue",
    runtimeHandlerId: "runtime.diagnostic.sensorNotImplemented",
    irV2Op: "sensor.colorValue",
  }),
  entry({
    type: "sensor_color_detected",
    category: "Sensor",
    displayText: "Color sensor port 1 detected red",
    kind: "boolean",
    fields: [
      field("port", "dropdown", "1", { values: PORTS }),
      field("color", "dropdown", "red", { values: COLORS }),
    ],
    runtimeStatus: "stub",
    generatorHandlerId: "sensor.colorDetected",
    runtimeHandlerId: "runtime.diagnostic.sensorNotImplemented",
    irV2Op: "sensor.colorDetected",
  }),
];
